# Generated by Django 4.2.4 on 2023-11-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_hash", models.CharField(max_length=512)),
                ("last_block_hash", models.CharField(max_length=512)),
                ("from_address", models.CharField(max_length=512)),
                ("to_address", models.CharField(max_length=512)),
                ("amount", models.IntegerField()),
                ("signature", models.CharField(max_length=1024)),
                ("random_num", models.IntegerField()),
            ],
        ),
    ]
