# Generated by Django 4.2.4 on 2023-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="index",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
